--------------------------------------------------------
--  File created - Monday-October-29-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MULECODEGENTOOLTRACKER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MULECODEGENTOOLTRACKER" 
   (	"TRACKINGID" NUMBER(*,0), 
	"TRACKINGSTATUS" VARCHAR2(500 BYTE), 
	"TRACKINGDESCRIPTION" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.MULECODEGENTOOLTRACKER
SET DEFINE OFF;
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (79353,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (75377,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (53388,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (83436,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (80141,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (86920,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (74747,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (71477,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (51457,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (57606,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (52553,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (87816,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (76695,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (57489,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (79094,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (50748,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (78941,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (66990,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (66535,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (74229,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (72608,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (51903,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (82605,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (86709,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (61105,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (65485,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (82756,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (61169,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (76511,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (53474,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (69324,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (62939,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (70730,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (55527,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (86164,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (72329,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (71428,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (74834,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (73764,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (70437,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (64325,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (66729,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (54501,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (86666,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (69384,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (72848,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (50346,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (78472,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (78548,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (66731,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (87451,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (85104,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (70681,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (67510,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (64061,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (57408,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (70138,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (52842,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (79273,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (78467,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (60989,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (79111,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (65511,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (79103,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (65571,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (64894,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (63817,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (62967,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (77582,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (54767,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (60173,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (76175,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (84733,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (89603,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (50272,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (87322,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (59597,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (55957,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (58790,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (88209,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (69653,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (83186,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (55047,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (67991,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (82377,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (65278,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (72614,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (80991,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (69706,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (81981,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (87454,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (60962,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (56209,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (62773,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (76333,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (73598,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (52520,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (81281,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (70943,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (71205,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (73093,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (66090,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (56032,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (51948,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (57134,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (84349,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (79094,'Success','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (87413,'Pending','Tracking is ON','teksystems@gmail.com');
Insert into SYSTEM.MULECODEGENTOOLTRACKER (TRACKINGID,TRACKINGSTATUS,TRACKINGDESCRIPTION,EMAIL) values (68062,'Success','Tracking is ON','teksystems@gmail.com');


